spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
  mail:
    sender:
      address: todo@gmail.com
    host: ${SMTP_HOST}
    port: ${SMTP_PORT}
    username: ${SMTP_USERNAME}
    password: ${SMTP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  application:
    name: danekerscode-api
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
  liquibase:
    enabled: false
  mvc:
    log-request-details: true
logging:
  level:
    org:
      springframework:
        web: debug
aes:
  transformation: 'AES'
  algorithm: "AES"
  secret: "7134743777217A25432A462D4A614E64" # 32 bytes

application:
  admin:
    username: bestadmin@gmail.com
    password: strongerrr

server:
  servlet:
    context-path: /api/v1/
  port: 443