CREATE TABLE customer
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created        TIMESTAMP WITHOUT TIME ZONE,
    updated        TIMESTAMP WITHOUT TIME ZONE,
    added_by_admin BOOLEAN,
    name           VARCHAR(255),
    surname        VARCHAR(255),
    email          VARCHAR(255),
    gender         VARCHAR(255),
    image_url      VARCHAR(255),
    CONSTRAINT pk_customer PRIMARY KEY (id)
);