CREATE TABLE product
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created        TIMESTAMP WITHOUT TIME ZONE,
    updated        TIMESTAMP WITHOUT TIME ZONE,
    added_by_admin BOOLEAN,
    name           VARCHAR(255),
    rating         FLOAT,
    price          DECIMAL,
    category       VARCHAR(255),
    image_url      VARCHAR(255),
    CONSTRAINT pk_product PRIMARY KEY (id)
);