CREATE TABLE image
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created        TIMESTAMP WITHOUT TIME ZONE,
    updated        TIMESTAMP WITHOUT TIME ZONE,
    added_by_admin BOOLEAN,
    base_64_data   VARCHAR(255),
    name           VARCHAR(255),
    CONSTRAINT pk_image PRIMARY KEY (id)
);