CREATE TABLE "user"
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email          VARCHAR(255),
    api_key        VARCHAR(255),
    email_verified BOOLEAN,
    otp            INTEGER,
    CONSTRAINT pk_user PRIMARY KEY (id)
);